"""Helper functions for the CodeGraph CLI.

This module re-exports from ``codegraph.cli.commands`` for backward compatibility.
"""

from codegraph.cli.commands import (
    _claude_desktop_config_paths,
    _claude_json_has_codegraph,
    _find_mcp_registrations,
    _gemini_settings_has_codegraph,
    _gemini_settings_paths,
    _initialize_db,
    _mcp_json_has_codegraph,
    _read_build_timestamp,
    _write_build_timestamp,
    _write_claude_desktop_json,
    _write_env_password,
    _write_gemini_settings_json,
    _write_project_mcp_json,
    doctor_helper,
    explain_helper,
    init_helper,
    install_helper,
    query_helper,
    rebuild_helper,
    stats_helper,
    status_helper,
    visualize_helper,
    watch_helper,
)

__all__ = [
    "_claude_desktop_config_paths",
    "_claude_json_has_codegraph",
    "_find_mcp_registrations",
    "_gemini_settings_has_codegraph",
    "_gemini_settings_paths",
    "_initialize_db",
    "_mcp_json_has_codegraph",
    "_read_build_timestamp",
    "_write_build_timestamp",
    "_write_claude_desktop_json",
    "_write_env_password",
    "_write_gemini_settings_json",
    "_write_project_mcp_json",
    "doctor_helper",
    "explain_helper",
    "init_helper",
    "install_helper",
    "query_helper",
    "rebuild_helper",
    "stats_helper",
    "status_helper",
    "visualize_helper",
    "watch_helper",
]
